version: 0.0
os: linux
files:
  - source: /
    destination: /tmp/codedeploy-deployment-staging-area/
hooks:
  ApplicationStop:
    - location: awsscripts/stop_application.sh
      timeout: 300
  BeforeInstall:
    - location: awsscripts/install_nginx.sh
      timeout: 300
  ApplicationStart:
    - location: awsscripts/aws_codedeploy_config.sh
    - location: awsscripts/start_application.sh
      timeout: 300
