version: 0.1
phases:
  install:
    commands:
      - npm install -g bower
      - npm install -g grunt-cli
      - bower install --allow-root
      - npm install --save-dev @angular/cli@latest
      - gem sources -a http://rubygems.org
      - gem install bundler
      - bundle install
     
# Create a production ready artifact
    
#      - echo CODEBUILD_SRC_DIR - $CODEBUILD_SRC_DIR
  pre_build:
    commands:
      - grunt prod
#     - tar -cvf angularCodeDependencies.tar $CODEBUILD_SRC_DIR
#     - tar -cvf angularCodeDependencies.tar .
#     - echo Creating dist folder for copying all the angular code as well as dependencies
#     - mkdir dist
#     - tar -xvf angularCodeDependencies.tar -C dist
artifacts:
  files:
      - dist/**/*
      - awsscripts/install_dependencies.sh
      - awsscripts/start_application.sh
      - awsscripts/stop_application.sh
      - awsscripts/aws_codedeploy_config.sh
      - appspec.yml
discard-paths: yes
