version: 0.1
phases:
  install:
    commands:
      - npm install -g bower
      - npm install -g grunt-cli
      - bower install --allow-root
      - npm install --save-dev @angular/cli@latest
      - echo CODEBUILD_SRC_DIR - $CODEBUILD_SRC_DIR
  pre_build:
    commands:
      - tar -cvf angularCodeDependencies.tar $CODEBUILD_SRC_DIR
      - echo Creating dist folder for copying all the angular code as well as dependencies
      - mkdir dist
      - tar -xvf angularCodeDependencies.tar -C dist
artifacts:
  files:
      - dist/**/*
base-directory: mifosFrontend     
discard-paths: yes
